spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-htao-dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-htao-test
#请保存为UTF-8格式